os:
  - linux
  - osx
matrix:
  include:
    - os: osx
      osx_image: xcode8.3
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - yarn
env:
  - NODE_VERSION="9"
script:
  - ./scripts/travis-setup.sh
  - yarn
  - cd npm-package && yarn && cd ..
  - yarn lint
  - yarn build
  - yarn test
  - yarn test-e2e
