build: off

os: unstable

environment:
  nodejs_version: '7'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn --ignore-scripts
  - cd dist && yarn && cd ..
  - cd npm-package && yarn && cd ..

test_script:
  - node --version
  - yarn --version
  - yarn lint
  - yarn build
  - yarn test
